django-user/mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('polls.urls')),
    url(r'^polls/', include('polls.urls')),

    url(r'^admin/', admin.site.urls),
]
'''
urlpatterns = [
    url(r'^admin/', admin.site.urls),
]
'''

django-user/mysite/polls/urls.py
from django.conf.urls import url

from . import views

app_name='polls'

urlpatterns = [
    # ex: /polls/
    url(r'^$', views.login_form, name='login_form'),
    url(r'^login/', views.login_form, name='login_form'),
    url(r'^login_view/', views.login_view, name='login_view'),

    url(r'^index/', views.index, name='index'),
    url(r'^logout/', views.logout_view, name='logout'),

    url(r'^signup/', views.signup_form, name='signup_form'),
    url(r'^signup_view/', views.signup_view, name='signup_view'),
    url(r'^add_question/', views.add_question, name='add_question'),
    url(r'^save_question/', views.save_question, name='save_question'),


    # ex: /polls/5/
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),

    url(r'^(?P<question_id>[0-9]+)/comment/$', views.comment, name='comment'),
]


'''
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]
'''

django-user/mysite/polls/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
import datetime
from django.contrib.auth import login,authenticate,logout
from django.contrib.auth.models import User

# Create your models here.



class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    username = models.CharField(max_length=200,default="anonymous")
    def __str__(self): 
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'
        



class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text


class Comment(models.Model):
	question=models.ForeignKey(Question,on_delete=models.CASCADE)
	user=models.CharField(max_length=200,default='none')
	comment_text=models.CharField(max_length=200)
	def __str__(self):
		return self.comment_text
	

django-user/mysite/polls/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
from .models import Question
from django.template import loader
from django.http import Http404
from django .core.urlresolvers import reverse
from django.views import generic
from django.contrib.auth import login,authenticate,logout
from django.contrib.auth.models import User
from django.utils import timezone


'''
def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    template = loader.get_template('polls/index.html')
    context = {
        'latest_question_list': latest_question_list,
    }
    return HttpResponse(template.render(context, request))
'''

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')
    f_question=get_object_or_404(Question,pk=1)
    context = {'latest_question_list': latest_question_list,'f_question':f_question,'user':request.user}
    return render(request, 'polls/index.html', context)



# Create your views here.
'''
def detail(request, question_id):
    return HttpResponse("You're looking at question %s." % question_id)
'''

'''
def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, 'polls/detail.html', {'question': question})   
'''

def detail(request, question_id):
    latest_question_list = Question.objects.order_by('-pub_date')
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/index.html', {'f_question': question,'latest_question_list':latest_question_list,'user':request.user})     
    
'''
def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)
'''

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/index.html', {'question': question})  

def login_form(request):
    return render(request,'polls/login.html')    

def login_view(request):
    
    uname=request.POST['username']
    passd=request.POST['password']
    user=authenticate(username=uname,password=passd)
    if user is not None:
        if user.is_active:
            login(request,user)
            return HttpResponseRedirect(reverse('polls:index'))        

            

                

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('polls:login_form'))  

def signup_view(request):
    uname=request.POST['username']
    passd=request.POST['password']
    email=request.POST['email']

    user = User.objects.create_user(uname, email, passd)
    user.first_name=request.POST['first_name']
    user.last_name=request.POST['last_name']
    user.save()
    return HttpResponseRedirect(reverse('polls:login_form'))  

def signup_form(request):
    return render(request,'polls/signup.html') 

def add_question(request):
    return render(request,'polls/add.html') 

def save_question(request):
    q_text=request.POST['question']
    c1=request.POST['choice1']
    c2=request.POST['choice2']
    c3=request.POST['choice3']

    q=Question(question_text=q_text,pub_date=timezone.now(),username=request.user.username)
    q.save()
    q.choice_set.create(choice_text=c1,votes=0)
    q.choice_set.create(choice_text=c2,votes=0)
    q.choice_set.create(choice_text=c3,votes=0)

    return HttpResponseRedirect(reverse('polls:add_question')) 







          




'''
class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'
'''
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:detail', args=(question.id,)))

def comment(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    cmn=""
    try:
        cmn = request.POST['comment']
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        c=question.comment_set.create(comment_text=cmn,user=request.user.username)
        c.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:detail', args=(question.id,)))        

django-user/mysite/polls/templates/polls/add.html
{% load staticfiles %}


<!DOCTYPE html>
<html lang="en">
<head>
  <title>Virtual Poll:Speak your mind</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <!--<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" /> 
  -->
  <style>
    /* Remove the navbar's default margin-bottom and rounded borders */ 
    .navbar {
      
      border-radius: 0;
    }
    
    /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
    .row.content {height: 450px}
    
    /* Set gray background color and 100% height */
    .sidenav {
      padding-top: 20px;
      background-color: #f1f1f1;
      height: 100%;
    }
    .profpic {

      margin-right : 25px;
      padding : 10px;
    }
    #roller-info{

      font-size: 15px
      margin-bottom:30px;
      padding: 0px
      

    }
    #tip-info{

      font-size: 15px
      margin-bottom:30px;
      padding : 20px 
      

    }
    #super-info{

      font-size: 15px
      margin-bottom:30px;
      padding: 0px


    }

    
    

    #hello {

      font-family: arial black;
      font-style:italic;

    }
    #about{

      font-size:24px;
    }
    #col-header{

      font-family:verdana;
      font-size:18px;
      font-style:bold;
      text-align: center;
    }
    
    /* Set black background color, white text and some padding */
    footer {
      background-color: #555;
      color: white;
      padding: 15px;
    }
    
    /* On small screens, set height to 'auto' for sidenav and grid */
    @media screen and (max-width: 767px) {
      .sidenav {
        height: auto;
        padding: 15px;
      }
      .row.content {height:auto;} 
    }

    #col-body{

      font-family: verdana;
      font-size: 18px;
      text-align: center;
    }
    #other{

      font-family: verdana;
      font-size: 18px;
      margin-bottom: 10px;
      margin-left:20px;
      padding-right:50px;
    }
    #otherlast{

      font-family: verdana;
      font-size: 18px;
      margin-bottom: 100px;
      margin-left: 20px;
      padding-right: 50px
    }
    .right{

      padding-right: 20px;
    }

    #label
    {
    	text-align: left;
    	font-size : 18px;
    	font-family : verdana;
    }
    #textarea
    {
    	padding-left : 20px;
    	padding-right : 20px;
    }
    #panel-body
    {
    	/*padding-left : 20px;
    	padding-right : 20px;*/	
    }
    #user_info
    {
    	font-size:20px;
    	font-family:verdana;
    	
    }
    #body
    {
    	margin-bottom: 400px;
    }
    



    
  </style>
</head>
<body id="body">

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Virtual Poll</a>
    </div>
    <ul class="nav navbar-nav">
      <li ><a href="{% url 'polls:index' %}">Home</a></li>
      <li class="active"><a href="#">Add question</a></li>
      
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="{% url 'polls:logout' %}"><span class="glyphicon glyphicon-user"></span> Log out</a></li>
      
    </ul>
  </div>
</nav>

<div class="container">
  <form role='form' method='POST' action="{% url 'polls:save_question' %}">
    {% csrf_token %}
    <div class='form-group'>
      <div class="row">
          <div class="col-sm-4">
           <div class="col-body">
            <label for="question">Add question</label>
            <textarea class="form-control" id='question' name='question' row='10' ></textarea>
           </div> 
          </div>
          <div class="col-sm-8">
            <div class="col-body">
            <label for="choice1">Add choice 1</label>
            <input type="text" id='choice1' name='choice1' class='form-control' >
            </br>
            <label for="choice1">Add choice 2</label>
            <input type="text" id='choice2' name='choice2' class='form-control' >
            </br>
            <label for="choice1">Add choice 3</label>
            <input type="text" id='choice3' name='choice3' class='form-control' >
            </br>
            <input type="submit" value="Save question" class="btn btn-primary">
            </div>


          </div>
     </div>
    </div>
  </form>
</div>

</body>
</html>

django-user/mysite/polls/templates/polls/detail.html
<!--
<h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul>
-->

<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

django-user/mysite/polls/templates/polls/index.html
{% load staticfiles %}


<!DOCTYPE html>
<html lang="en">
<head>
  <title>Virtual Poll:Speak your mind</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <!--<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" /> 
  -->
  <style>
    /* Remove the navbar's default margin-bottom and rounded borders */ 
    .navbar {
      
      border-radius: 0;
    }
    
    /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
    .row.content {height: 450px}
    
    /* Set gray background color and 100% height */
    .sidenav {
      padding-top: 20px;
      background-color: #f1f1f1;
      height: 100%;
    }
    .profpic {

      margin-right : 25px;
      padding : 10px;
    }
    #roller-info{

      font-size: 15px
      margin-bottom:30px;
      padding: 0px
      

    }
    #tip-info{

      font-size: 15px
      margin-bottom:30px;
      padding : 20px 
      

    }
    #super-info{

      font-size: 15px
      margin-bottom:30px;
      padding: 0px


    }

    
    

    #hello {

      font-family: arial black;
      font-style:italic;

    }
    #about{

      font-size:24px;
    }
    #col-header{

      font-family:verdana;
      font-size:18px;
      font-style:bold;
      text-align: center;
    }
    
    /* Set black background color, white text and some padding */
    footer {
      background-color: #555;
      color: white;
      padding: 15px;
    }
    
    /* On small screens, set height to 'auto' for sidenav and grid */
    @media screen and (max-width: 767px) {
      .sidenav {
        height: auto;
        padding: 15px;
      }
      .row.content {height:auto;} 
    }

    #col-body{

      font-family: verdana;
      font-size: 18px;
      text-align: center;
    }
    #other{

      font-family: verdana;
      font-size: 18px;
      margin-bottom: 10px;
      margin-left:20px;
      padding-right:50px;
    }
    #otherlast{

      font-family: verdana;
      font-size: 18px;
      margin-bottom: 100px;
      margin-left: 20px;
      padding-right: 50px
    }
    .right{

      padding-right: 20px;
    }

    #label
    {
    	text-align: left;
    	font-size : 18px;
    	font-family : verdana;
    }
    #textarea
    {
    	padding-left : 20px;
    	padding-right : 20px;
    }
    #panel-body
    {
    	/*padding-left : 20px;
    	padding-right : 20px;*/	
    }
    #user_info
    {
    	font-size:20px;
    	font-family:verdana;
    	
    }
    #body
    {
    	margin-bottom: 400px;
    }
    #q_authordetails
    {
    	 font-size: 15px;
    	 font-family: verdana;
    	 font-style: italic;
    }
    
    
   #scrollablebody {
    
    overflow-y: scroll; 
  }

    



    
  </style>
</head>
<body id="body">

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Virtual Poll</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Home</a></li>
      <li><a href="{% url 'polls:add_question' %}">Add question</a></li>
      
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="{% url 'polls:logout' %}"><span class="glyphicon glyphicon-user"></span> Log out</a></li>
      
    </ul>
  </div>
</nav>
  
<div class="container">
<div id="user_info">
	Hello {{ user.username }}!!
</div>
  
  


 <div class="row">
          <div class="col-sm-4">
            <div class="page-header" id='col-header'>
              Choose a Question
            </div>
            <div id="col-body" id="scrollablebody">
            	
            		<div class='panel panel-default'>
            			
            			<div class='panel-body'> 
		              		{% if latest_question_list %}

			    				<div class='list-group'>
				    				{% for question in latest_question_list %}
				        				<a href="{% url 'polls:detail' question.id %}" class='list-group-item'>{{ question.question_text }}</a>

				    				{% endfor %}
				    			</div>	
				  					{% else %}
				    					<p>No polls are available.</p>
				  					{% endif %}
				  		</div>			
			  		</div>		
		  				
		  				
	  					
            
          </div>
          </div>
          <div class="col-sm-8">
            <div class="page-header" id="col-header">
              Question details
            </div>
            <div id="col-body">
            		<div class='panel panel-default'>
            			<div class='panel-heading'>
            				<div class="row">
            					<div class='col-sm-4'>
            						<div class="col-body">
            							<div id="q_authordetails">
            								Auther:{{ f_question.username }}
            								</br>
            								{{ f_question.pub_date }}
            							</div>	
            						</div>
            					</div>
            					<div class='col-sm-4'>
            						<div class="col-body">
            								{{ f_question.question_text }}
            						</div>
            					</div>
            				</div>

            			</div>
            			
            			<div class='panel-body' id="panel-body">
		              				<form action="{% url 'polls:vote' f_question.id %}" method="post" class='form-horizontal' role="form">
		              				<div class="form-group">
									{% csrf_token %}
										<div class="list-group">
										{% for choice in f_question.choice_set.all %}
											<li class="list-group-item">
										    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
										    <label for="choice{{ forloop.counter }}" >{{ choice.choice_text }} </label>
										    </li>
										{% endfor %}
										</div>
										<input type="submit" value="Vote" class="btn btn-primary btn-sm" />

										</div>
									</form>
									<button data-toggle="collapse" data-target="#showcomments" class="btn btn-info btn-block btn-sm"> Show comments</button>
									<div class="Well collapse" id="showcomments">
									<div class="list-group">
										{% for comment in f_question.comment_set.all %}

											<li class="list-group-item">
												<div class="row">
         											 <div class="col-sm-4">
         											 	<div class="col-body">
         											 		{{ comment.user }} :
         											 	</div>
         											 </div>
         											 <div class="col-sm-4">
         											 	<div class="col-body">
         											 		{{ comment.comment_text }}
         											 	</div>
         											 </div>
         										</div>	 			
												

											</li>
										{% endfor %}	
									</div>
										


									</div>
									</br>

									<button data-toggle="collapse" data-target="#form-comment" class="btn btn-primary btn-block btn-sm"> Add comment</button>
									</br>
									<form action="{% url 'polls:comment' f_question.id %}" method="post" class="form-horizontal collapse" role="form" id="form-comment">
										<div class="form-group">
											{% csrf_token %}
											<div id="textarea">

											<textarea class="form-control" rows="5" id="comment" name="comment" ></textarea>
											</div>
											</br>
											<input type="submit" value="Post" class="btn btn-primary btn-sm" />
											
										</div>
									</form>

			    				
				  		</div>			
			  		</div>
				<button data-toggle='collapse' data-target='#results' class="btn btn-info btn-block btn-sm"> Click to view results</button> 
           		<div class="Well collapse" id="results">
		            	<ul class="list-group" >
		            	{% for choice in f_question.choice_set.all %}
								<li class="list-group-item"><span class="badge">{{ choice.votes }}</span> {{ choice.choice_text }}</li>
						{% endfor %}

						</ul>	
				</div>							
            	
            
          </div>	
              
            </div>
            
          
</div>  
</div>
</body>       
</html>

django-user/mysite/polls/templates/polls/login.html
{% load staticfiles %}


<!DOCTYPE html>
<html lang="en">
<head>
  <title>Virtual Poll:Speak your mind</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <!--<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" /> 
  -->
  <style>
    /* Remove the navbar's default margin-bottom and rounded borders */ 
    .navbar {
      
      border-radius: 0;
    }
    
    /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
    .row.content {height: 450px}
    
    /* Set gray background color and 100% height */
    .sidenav {
      padding-top: 20px;
      background-color: #f1f1f1;
      height: 100%;
    }
    .profpic {

      margin-right : 25px;
      padding : 10px;
    }
    #roller-info{

      font-size: 15px
      margin-bottom:30px;
      padding: 0px
      

    }
    #tip-info{

      font-size: 15px
      margin-bottom:30px;
      padding : 20px 
      

    }
    #super-info{

      font-size: 15px
      margin-bottom:30px;
      padding: 0px


    }

    
    

    #hello {

      font-family: arial black;
      font-style:italic;

    }
    #about{

      font-size:24px;
    }
    #col-header{

      font-family:verdana;
      font-size:18px;
      font-style:bold;
      text-align: center;
    }
    
    /* Set black background color, white text and some padding */
    footer {
      background-color: #555;
      color: white;
      padding: 15px;
    }
    
    /* On small screens, set height to 'auto' for sidenav and grid */
    @media screen and (max-width: 767px) {
      .sidenav {
        height: auto;
        padding: 15px;
      }
      .row.content {height:auto;} 
    }

    #col-body{

      font-family: verdana;
      font-size: 18px;
      text-align: center;
    }
    #other{

      font-family: verdana;
      font-size: 18px;
      margin-bottom: 10px;
      margin-left:20px;
      padding-right:50px;
    }
    #otherlast{

      font-family: verdana;
      font-size: 18px;
      margin-bottom: 100px;
      margin-left: 20px;
      padding-right: 50px
    }
    .right{

      padding-right: 20px;
    }

    #label
    {
    	text-align: left;
    	font-size : 18px;
    	font-family : verdana;
    }
    #textarea
    {
    	padding-left : 20px;
    	padding-right : 20px;
    }
    #panel-body
    {
    	/*padding-left : 200px;
    	padding-right : 400px;
      */
    }
    #body
    {
        text-align: center;
        padding-left: 400px;
        padding-right: 400px;
        padding-top:160px;

    }
  </style>
</head>
<body id="body">

  <div class="panel panel-default">
    <div class="panel-body" id="panel-body">


      
     
        <ul class="nav nav-pills">
        <li class="active"><a href="#"> Log in</a></li>
        <li ><a href="{% url 'polls:signup_form' %}"> Sign up</a></li>
      </ul>
      </br>
        <form role="form" method="POST" action="{% url 'polls:login_view' %}">
          <div class="form-group">
          {% csrf_token %}
          <label for="username">Username</label>
            <input type="text" name="username" id="username" class="form-control" >
            </br>

             <label for="password">Password</label>

            <input type="password" name="password" id="password" class="form-control">
            </br>
            <input type="submit" value="Log in" class="btn btn-primary">
           
          </div>
        </form>
        
    </div>  
  </div>

</body>
</html>

django-user/mysite/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

django-user/mysite/polls/templates/polls/signup.html
{% load staticfiles %}


<!DOCTYPE html>
<html lang="en">
<head>
  <title>Virtual Poll:Speak your mind</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <!--<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" /> 
  -->
  <style>
    /* Remove the navbar's default margin-bottom and rounded borders */ 
    .navbar {
      
      border-radius: 0;
    }
    
    /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
    .row.content {height: 450px}
    
    /* Set gray background color and 100% height */
    .sidenav {
      padding-top: 20px;
      background-color: #f1f1f1;
      height: 100%;
    }
    .profpic {

      margin-right : 25px;
      padding : 10px;
    }
    #roller-info{

      font-size: 15px
      margin-bottom:30px;
      padding: 0px
      

    }
    #tip-info{

      font-size: 15px
      margin-bottom:30px;
      padding : 20px 
      

    }
    #super-info{

      font-size: 15px
      margin-bottom:30px;
      padding: 0px


    }

    
    

    #hello {

      font-family: arial black;
      font-style:italic;

    }
    #about{

      font-size:24px;
    }
    #col-header{

      font-family:verdana;
      font-size:18px;
      font-style:bold;
      text-align: center;
    }
    
    /* Set black background color, white text and some padding */
    footer {
      background-color: #555;
      color: white;
      padding: 15px;
    }
    
    /* On small screens, set height to 'auto' for sidenav and grid */
    @media screen and (max-width: 767px) {
      .sidenav {
        height: auto;
        padding: 15px;
      }
      .row.content {height:auto;} 
    }

    #col-body{

      font-family: verdana;
      font-size: 18px;
      text-align: center;
    }
    #other{

      font-family: verdana;
      font-size: 18px;
      margin-bottom: 10px;
      margin-left:20px;
      padding-right:50px;
    }
    #otherlast{

      font-family: verdana;
      font-size: 18px;
      margin-bottom: 100px;
      margin-left: 20px;
      padding-right: 50px
    }
    .right{

      padding-right: 20px;
    }

    #label
    {
    	text-align: left;
    	font-size : 18px;
    	font-family : verdana;
    }
    #textarea
    {
    	padding-left : 20px;
    	padding-right : 20px;
    }
    #panel-body
    {
    	/*padding-left : 200px;
    	padding-right : 400px;
      */
    }
    #body
    {
        text-align: center;
        padding-left: 400px;
        padding-right: 400px;
        padding-top:160px;

    }
  </style>
</head>
<body id="body">

  <div class="panel panel-default">
    <div class="panel-body" id="panel-body">


      
     
        <ul class="nav nav-pills">
        <li ><a href="{% url 'polls:login_form' %}"> Log in</a></li>
        <li class="active"><a href="#"> Sign up</a></li>
      </ul>
      </br>
        <form role="form" method="POST" action="{% url 'polls:signup_view' %}">
          <div class="form-group">
          {% csrf_token %}
          <label for="first_name">First name</label>
          <input type="text" name="first_name" id="first_name" class="form-control">
          </br>
          <label for="last_name">Last name</label>
          <input type="text" name="last_name" id="last_name" class="form-control">
          </br>
          <label for="username">Username</label>
            <input type="text" name="username" id="username" class="form-control" >
            </br>
             <label for="email">Email</label>

            <input type="text" name="email" id="email" class="form-control">
            </br>
             <label for="password">Password</label>

            <input type="password" name="password" id="password" class="form-control">

            </br>
            <input type="submit" value="Sign up" class="btn btn-primary">
           
          </div>
        </form>
        
    </div>  
  </div>

</body>
</html>